public class Antics {

    public static boolean isPalindrome(String word) {
        
        return true;
    }
   
    public static boolean isAbecedarian(String word) {
        
        return true;
    }
   
    public static boolean isPangram(String sentence) {
        
        return true;
    }
    
    public static String capitalizeFirstLetter(String sentence) {
        
        return sentence;
    }

}